# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Derby Makers Blog
tagline:             ''
description:         "A devoted group of hackers and makers in the world's first factory; Derby Silk Mill."
url:                 http://derbymakers.github.io/blog
baseurl:             'http://derbymakers.github.io/blog'
paginate:            5

# About/contact
author:
  name:              Derby Makers
  url:               http://derbymakers.github.io

# Custom vars
version:             1.0.0
